### ISSUE TITLE
Fails with certain variables

### ISSUE THREAD

**Issue by shimizurei** [seethroughdev/obsidian-recipe-grabber#27]
FM template

```yaml
---
published: {{magicTime datePublished "yyyymmdd"}}
prep_time: {{magicTime prepTime}}
cooking_time: {{magicTime cookTime}}
total_time: {{magicTime totalTime}}
servings: {{{recipeYield}}}
macros:
  - calories: {{{nutrition.calories}}}
  - carbs: " grams"
  - protein: " grams"
  - fat: " grams"
description: |
    {{description}}
tags:
- {{{recipeCuisine}}}
- {{{recipeCategory}}}
{{splitTags keywords}}
```

[Recipe in question](https://www.loveandlemons.com/brownies-recipe/)

If I keep any of the lines using `{{magicTime}}` or `{{splitTags keywords}}`, the import will fail. Am I not using them correctly?
