### ISSUE TITLE
Variables using "magicTime" result in a trailing space

### ISSUE THREAD

**Issue by shimizurei** [seethroughdev/obsidian-recipe-grabber#38]
From my template:

```yaml
prep_time: "{{magicTime prepTime}}"
cooking_time: "{{magicTime cookTime}}"
total_time: "{{magicTime totalTime}}"
```

Input data:

```json
"cookTime": "PT15M",
"prepTime": "PT20M",
"totalTime": "PT1H5M"
```

Output:

```yaml
prep_time: "20m "
cooking_time: "15m "
total_time: "1h 5m "
```

I think the issue is with this section in `main.ts`:

```typescript
if (arg1.trim().startsWith("PT")) {
  // magicTime PT1H50M
  return arg1
    .trim()
    .replace("PT", "")
    .replace("H", "h ")
    .replace("M", "m ")
    .replace("S", "s ");
}
```

Maybe a final `.trim()`? (idk TS/JS is not my thing)
